name: Deploy FastAPI to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Stop old container (jika ada)
      - name: Stop old container
        run: |
          docker compose down || true

      # 3. Build & start container
      - name: Build and Start Docker
        run: |
          docker compose up -d --build

      # 4. Check running container
      - name: Check containers
        run: |
          docker ps

      # 5. Simple health check (optional tapi penting)
      - name: Health Check API
        run: |
          sleep 10
          curl -f http://localhost:8000/docs || exit 1
