name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${ secrets.VPS_HOST }
          username: ${ secrets.VPS_USER }
          key: ${ secrets.VPS_SSH_KEY }
          source: "."
          target: "~/apps/be_amd"

      - name: SSH deploy docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${ secrets.VPS_HOST }
          username: ${ secrets.VPS_USER }
          key: ${ secrets.VPS_SSH_KEY }
          script: |
            cd ~/apps/be_amd

            echo "Stopping old containers..."
            docker compose down

            echo "Building new image..."
            docker compose build

            echo "Starting containers..."
            docker compose up -d

            echo "Cleanup..."
            docker image prune -f
